DATASET:
   SRC: "mnist"
   TGT: "usps"
SRC_NET:
   ARCH: "DTN"
   SRC_LR: 0.0001
   SRC_EPOCH: 300
   BATCH_SIZE: 128
   NUM_CLS: 10
   WEIGHTS: ""   
TRAIN:
   GPU_ID: 0
   DATA_DIR: "."
   RESULT_DIR: "results"
   NUM_WORKERS: 1
   TASK: "classification"
OPTIMIZER:
    ADAM:
       BETAS: (0.9,0.999)
       WEIGHT_DECAY: 0.0005
CALIBRATOR:
   CALI_EPOCH: 200
   BATCH_SIZE: 128   
   CALI_LR: 0.0001
   ARCH: "resnet_9"
   NORM_TYPE: "instance"
   L_INFTY_NORM: 0.4
   CALI_WIDTH_FACTOR: 8
   PATCH_SIZE: 4
   RESOLUTION: 16
   USE_SOFTMAX: True
   USE_PIXEL: True
   WEIGHTS: ""
   BOX_MIN: -1
   BOX_MAX: 1